---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-example-3
  namespace: eks-example
  labels:
    app: eks-example-3
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-example-3
  template:
    metadata:
      labels:
        app: eks-example-3
    spec:
      containers:
      - name: eks-example-3
        image: 371162891584.dkr.ecr.ap-southeast-1.amazonaws.com/eks-example:e4390866
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
