---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: fargate-only-cluster
  region: ap-southeast-1
fargateProfiles:
  - name: eksexample-fargate-profile
    selectors:
      - namespace: eks-example
